//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Brand. All Rights Reserved.
        /// </summary>
        internal static string blue_Copyright {
            get {
                return ResourceManager.GetString("blue_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string blue_Description {
            get {
                return ResourceManager.GetString("blue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string blue_Disclaimer {
            get {
                return ResourceManager.GetString("blue_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk: +1 222.222.2222.
        /// </summary>
        internal static string blue_Helpdesk {
            get {
                return ResourceManager.GetString("blue_Helpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string blue_Logo {
            get {
                return ResourceManager.GetString("blue_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Universal Login Page.
        /// </summary>
        internal static string blue_Name {
            get {
                return ResourceManager.GetString("blue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Login Page.
        /// </summary>
        internal static string blue_NameShort {
            get {
                return ResourceManager.GetString("blue_NameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Universal Login Page.
        /// </summary>
        internal static string blue_Title {
            get {
                return ResourceManager.GetString("blue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Login Page.
        /// </summary>
        internal static string blue_TitleShort {
            get {
                return ResourceManager.GetString("blue_TitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ID.
        /// </summary>
        internal static string Error_ID {
            get {
                return ResourceManager.GetString("Error_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameter is missing or invalid..
        /// </summary>
        internal static string Error_RequiredParamterIsMissingOrInvalid {
            get {
                return ResourceManager.GetString("Error_RequiredParamterIsMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-try your action. If you continue to get this error, please contact the Administrator..
        /// </summary>
        internal static string Error_SystemException {
            get {
                return ResourceManager.GetString("Error_SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Brand. All Rights Reserved.
        /// </summary>
        internal static string green_Copyright {
            get {
                return ResourceManager.GetString("green_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt; &lt;p class=&quot;bhg1&quot;&gt;&lt;b&gt;Welcome to the Green Brand Login&lt;/b&gt;&lt;/p&gt; &lt;p&gt;&amp;nbsp;&lt;/p&gt; &lt;p class=&quot;bhg2&quot;&gt;This login will take you to all Green Brand products.&lt;/p&gt; &lt;p class=&quot;bhg2&quot;&gt;Your username is in the format of firstname.lastname@greenbrand.com&lt;/p&gt;.
        /// </summary>
        internal static string green_Description {
            get {
                return ResourceManager.GetString("green_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string green_Disclaimer {
            get {
                return ResourceManager.GetString("green_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk: (111) 111-1111.
        /// </summary>
        internal static string green_Helpdesk {
            get {
                return ResourceManager.GetString("green_Helpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string green_Logo {
            get {
                return ResourceManager.GetString("green_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Universal Login Page.
        /// </summary>
        internal static string green_Name {
            get {
                return ResourceManager.GetString("green_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Login Page.
        /// </summary>
        internal static string green_NameShort {
            get {
                return ResourceManager.GetString("green_NameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Universal Login Page.
        /// </summary>
        internal static string green_Title {
            get {
                return ResourceManager.GetString("green_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Login Page.
        /// </summary>
        internal static string green_TitleShort {
            get {
                return ResourceManager.GetString("green_TitleShort", resourceCulture);
            }
        }
    }
}
